name: llmsqler
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - transformers
  - datasets
  - accelerate
  - pip
  - pip:    
    - peft
    - bitsandbytes
    - trl
    - protobuf
    - tiktoken
    - psycopg2
    - faker
    - openai
    - redis
    